name: InsaneCommands
version: ${project.version}
main: me.itzdavidvzla.insanecommands.InsaneCommands
author: ItzDavidVZLA
website: https://github.com/Lably-Team
commands:
  insanecommands:
    description: General command of InsaneCommands
    aliases:
      - ic
      - icmd
  broadcast:
    description: Global message or alert of InsaneCommands
    aliases:
      - bc
      - alert
      - notify
  fly:
    description: Comando de Vuelo de InsaneCommands
  feed:
    description: Comando de Alimentacion de InsaneCommands
  heal:
    description: Comando de Curacion de InsaneCommands
  gmc:
    description: Comando de Modo de Juego de InsaneCommands
    aliases:
      - gamemodecreative
      - gmcreative
      - gamemodec
      - gamemode creative
  gms:
    description: Comando de Modo de Juego de InsaneCommands
    aliases:
      - gamemodesurvival
      - gmsurvival
      - gamemodes
      - gamemode survival
  gmsp:
    description: Comando de Modo de Juego de InsaneCommands
    aliases:
      - gamemodespectator
      - gmspectator
      - gamemodesp
      - gamemode spectator
  gma:
    description: Comando de Modo de Juego de InsaneCommands
    aliases:
      - gamemodeadventure
      - gmadventure
      - gamemodea
      - gamemode adventure
  spawn:
    description: Comando de Spawn de InsaneCommands
  setspawn:
    description: Comando de SetSpawn de InsaneCommands
  defaultcommand:
    description: test command
